name: 'Valist Action'
description: 'GitHub Action for publishing to Valist'
author: 'valist-io'
branding:
  icon: 'package'
  color: 'purple'

inputs:
  team:
    description: 'Valist team name'
    required: true
  project:
    description: 'Valist project name'
    required: true
  release:
    description: 'Valist release name'
    required: true
  files:
    description: 'Files to publish'
    required: true
  follow-symbolic-links:
    description: 'Follow symbolic links'
    default: true

runs:
  using: 'node14'
  main: 'index.js'
