name: 'Valist Publish'
description: 'Publish a release on valist'
runs:
  using: 'composite'
  steps:
    - run: ls
      shell: bash
    - run: chmod +x ./bin/valist
      shell: bash
    - run: valist publish --dryrun
      shell: bash
